apiVersion: v1
kind: Service
metadata:
  name: {{ include "laminar-dataplane.resourceName" "clickhouse" }}
  labels:
    {{- include "laminar-dataplane.labels" . | nindent 4 }}
    {{- include "laminar-dataplane.selectorLabels" (dict "name" "clickhouse" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8123
      targetPort: http
      protocol: TCP
    - name: native
      port: 9000
      targetPort: native
      protocol: TCP
  selector:
    {{- include "laminar-dataplane.selectorLabels" (dict "name" "clickhouse" "context" .) | nindent 4 }}
