apiVersion: v1
kind: Service
metadata:
  name: {{ include "laminar-dataplane.resourceName" "data-plane-proxy" }}
  labels:
    {{- include "laminar-dataplane.labels" . | nindent 4 }}
    {{- include "laminar-dataplane.selectorLabels" (dict "name" "data-plane-proxy" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "laminar-dataplane.selectorLabels" (dict "name" "data-plane-proxy" "context" .) | nindent 4 }}
