apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laminar-dataplane.resourceName" "dataplane-secrets" }}
  labels:
    {{- include "laminar-dataplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_URL: "http://{{ include "laminar-dataplane.resourceName" "clickhouse" }}:8123"
  CLICKHOUSE_USER: {{ .Values.clickhouse.user | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.password | quote }}
  CLICKHOUSE_DATABASE: {{ .Values.clickhouse.database | quote }}
  CLICKHOUSE_RO_USER: {{ .Values.clickhouse.user | quote }}
  CLICKHOUSE_RO_PASSWORD: {{ .Values.clickhouse.password | quote }}
  DATA_PLANE_PUBLIC_KEY: {{ .Values.dataPlaneProxy.dataPlanePublicKey | quote }}
