"""Values file generation and management for Helm."""

from typing import Dict, Any
from .constants import VALUES_FILE
from .yaml_utils import dict_to_yaml
from .ui import print_success


def build_values(config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Build the Helm values override dict from collected configuration.
    
    Args:
        config: Configuration dictionary from user input
        
    Returns:
        Dictionary structured for Helm values file
    """
    values = {
        'cloudProvider': config['cloud_provider'],
        'dataPlaneProxy': {
            'dataPlanePublicKey': config['data_plane_public_key'],
        },
        'clickhouse': {
            'password': config['clickhouse_password'],
        },
    }

    proxy = values['dataPlaneProxy']
    ch = values['clickhouse']

    if 'proxy_replicas' in config:
        proxy['replicaCount'] = config['proxy_replicas']
    
    if 'proxy_cpu' in config or 'proxy_memory' in config:
        resources = {}
        if 'proxy_cpu' in config:
            resources['requests'] = resources.get('requests', {})
            resources['limits'] = resources.get('limits', {})
            resources['requests']['cpu'] = config['proxy_cpu']
            resources['limits']['cpu'] = config['proxy_cpu']
        if 'proxy_memory' in config:
            resources['requests'] = resources.get('requests', {})
            resources['limits'] = resources.get('limits', {})
            resources['requests']['memory'] = config['proxy_memory']
            resources['limits']['memory'] = config['proxy_memory']
        proxy['resources'] = resources

    if 'lb_enabled' in config:
        lb = {'enabled': config['lb_enabled']}
        if config.get('lb_enabled'):
            if 'lb_port' in config:
                # lb_port is already an integer from get_int_input()
                lb['port'] = config['lb_port']
            if 'lb_annotations' in config and config['lb_annotations']:
                lb['annotations'] = config['lb_annotations']
        proxy['loadBalancer'] = lb

    if 'ch_cpu' in config or 'ch_memory' in config:
        resources = {}
        if 'ch_cpu' in config:
            resources['requests'] = resources.get('requests', {})
            resources['limits'] = resources.get('limits', {})
            resources['requests']['cpu'] = config['ch_cpu']
            resources['limits']['cpu'] = config['ch_cpu']
        if 'ch_memory' in config:
            resources['requests'] = resources.get('requests', {})
            resources['limits'] = resources.get('limits', {})
            resources['requests']['memory'] = config['ch_memory']
            resources['limits']['memory'] = config['ch_memory']
        ch['resources'] = resources

    if 'ch_storage_size' in config or 'ch_storage_class' in config:
        persistence = {}
        if 'ch_storage_size' in config:
            persistence['size'] = config['ch_storage_size']
        if 'ch_storage_class' in config:
            persistence['storageClass'] = config['ch_storage_class']
        ch['persistence'] = persistence

    if config.get('s3_enabled'):
        s3 = {
            'enabled': True,
            'endpoint': config['s3_endpoint'],
        }
        if 's3_region' in config:
            s3['region'] = config['s3_region']
        
        # For GCP, use HMAC keys if available
        if config['cloud_provider'] == 'gcp':
            if 'gcs_access_key_id' in config and 'gcs_secret_key' in config:
                s3['accessKeyId'] = config['gcs_access_key_id']
                s3['secretAccessKey'] = config['gcs_secret_key']
                s3['useEnvironmentCredentials'] = False
            elif 's3_access_key' in config and 's3_secret_key' in config:
                s3['accessKeyId'] = config['s3_access_key']
                s3['secretAccessKey'] = config['s3_secret_key']
                s3['useEnvironmentCredentials'] = False
        else:
            # AWS: use IAM or explicit keys
            if config.get('s3_use_env_creds'):
                s3['useEnvironmentCredentials'] = True
            elif 's3_access_key' in config and 's3_secret_key' in config:
                s3['accessKeyId'] = config['s3_access_key']
                s3['secretAccessKey'] = config['s3_secret_key']
        
        ch['s3'] = s3

    return values


def write_values_file_with_namespace(values: Dict[str, Any], namespace: str) -> None:
    """
    Write the values override file with namespace stored as a comment.
    
    Args:
        values: Values dictionary to write
        namespace: Kubernetes namespace
    """
    content = "# Generated by install.py - Laminar Data Plane configuration\n"
    content += f"# namespace: {namespace}\n"
    content += "# Edit this file and run 'python3 install.py --update-only' to apply changes.\n\n"
    content += dict_to_yaml(values)
    VALUES_FILE.write_text(content)
    print_success(f"Configuration written to {VALUES_FILE}")


def read_namespace_from_values() -> str:
    """
    Read the namespace from an existing laminar.yaml.
    
    Returns:
        Namespace string, defaults to 'default' if not found
    """
    if not VALUES_FILE.exists():
        return 'default'
    
    for line in VALUES_FILE.read_text().splitlines():
        if line.startswith('# namespace:'):
            return line.split(':', 1)[1].strip()
    
    return 'default'
